Repository hapipal/confidence, pull requests merged in 2018-11, with the labels that each got.

#80 code refactor and update deps
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  bin/confidence
  lib/index.js
  lib/store.js
  package.json
  test/bin.js
  test/id.js
  test/store.js
Labels: breaking changes

#83 Fix credentials typo
  README.md
Labels: documentation

#84 Use Joi error annotate instead of error message
  bin/confidence
Labels: enhancement

#85 Confidence v4
  README.md
  bin/confidence
  lib/schema.js
  lib/store.js
  package.json
  test/store.js
Labels: enhancement

#87 Add changelog.md
  CHANGELOG.md
Labels: documentation
